# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: local
    hooks:
      - id: ruff
        name: ruff (uv)
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format (uv)
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false

      - id: pylint
        name: pylint (uv)
        entry: uv run pylint
        language: system
        types: [python]
        args: ["-rn", "-sn", "--disable=import-error"]

      - id: mypy
        name: mypy (uv)
        entry: uv run mypy
        language: system
        types: [python]
        args: ["--explicit-package-bases", "--ignore-missing-imports"]
        pass_filenames: false

      - id: bandit
        name: bandit (uv)
        entry: uv run bandit -r . -c pyproject.toml
        language: system
        types: [python]
        pass_filenames: false
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
